pipeline {
    agent none
    parameters {
        string(name: 'CBL_VERSION', defaultValue: '3.3.0', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.2.3', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "Dotnet CBL:${params.CBL_VERSION} (#${currentBuild.number})"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
        stage('Prebuild Servers') {
            steps {
                build job: 'prebuild-test-server',
                parameters: [
                    string(name: 'TS_PLATFORM', value: 'dotnet_windows'),
                    string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                ],
                wait: true,
                propagate: true
            }
        }
        stage('Run Tests') {
            agent { label 'net-windows' }
            environment {
                TS_ARTIFACTS_DIR = 'dotnet_windows'
                TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
            }
            steps {
                echo "=== Run Dotnet Tests"
                timeout(time: 60, unit: 'MINUTES') {
                    powershell "jenkins\\pipelines\\QE\\dotnet\\run_test.ps1 -Version ${params.CBL_VERSION} -SgwVersion ${params.SGW_VERSION}"
                }
                echo "=== Dotnet Tests Complete"
            }
            post {
                always {
                    echo "=== Teardown Dotnet Tests"
                    timeout(time: 5, unit: 'MINUTES') {
                        powershell "jenkins\\pipelines\\QE\\dotnet\\teardown.ps1"
                    }
                    archiveArtifacts artifacts: 'tests\\QE\\dotnet_windows\\**\\*', fingerprint: true, allowEmptyArchive: true
                    echo "=== Dotnet Test Teardown Complete"
                }
            }
        }
    }
}
