pipeline {
    agent none
    parameters {
        string(name: 'CBL_VERSION', defaultValue: '3.3.0', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.3.0', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
    }
    options {
        timeout(time: 150, unit: 'MINUTES')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    
                    currentBuild.displayName = "C CBL:${params.CBL_VERSION} (#${currentBuild.number})"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
        stage('Prebuild Servers') {
            steps {
                script {
                    def platforms = [
                        'c_windows', 'c_ios', 'c_android', 'c_macos', 'c_linux_x86_64'
                    ]
                    def parallelBuilds = [:]
                    for(p in platforms) {
                        def platform = p
                        parallelBuilds[platform] = {
                            build job: 'prebuild-test-server',
                            parameters: [
                                string(name: 'TS_PLATFORM', value: platform),
                                string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                                string(name: 'BRANCH', value: 'qe-jenkins'),
                            ],
                            wait: true,
                            propagate: true
                        }
                    }
                    parallel parallelBuilds
                }
            }
        }
        stage('Run Tests') {
            parallel {
                stage('macOS') {
                    agent { label 'mac-mini-new' }
                    options {
                        lock('mac-mini-new')
                    }
                    environment {
                        PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        TS_ARTIFACTS_DIR = 'macos'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        // Unlock keychain:
                        withCredentials([string(credentialsId: 'mobile-qe', variable: 'KEYCHAIN_PASSWORD')]) {
                            sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        }
                        echo "=== Run C macOS Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/c/run_test.sh ${params.CBL_VERSION} macos ${params.SGW_VERSION}"
                        }
                        echo "=== C macOS Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown C macOS Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/c/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/c_macos/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== C macOS Test Teardown Complete"
                        }
                    }
                }
                stage('iOS') {
                    agent { label 'mac-mini-new' }
                    options {
                        lock('mac-mini-new,00008101-000E0519020A001E')
                    }
                    environment {
                        PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        TS_ARTIFACTS_DIR = 'ios'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        // Unlock keychain:
                        withCredentials([string(credentialsId: 'mobile-qe', variable: 'KEYCHAIN_PASSWORD')]) {
                            sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        }
                        echo "=== Run C iOS Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/c/run_test.sh ${params.CBL_VERSION} ios ${params.SGW_VERSION}"
                        }
                        echo "=== C iOS Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown C iOS Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/c/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/c_ios/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== C iOS Test Teardown Complete"
                        }
                    }
                }
                stage('Android') {
                    agent { label 'mac-mini-CBL-Android1' }
                    options {
                        lock('mac-mini-CBL-Android1,R5CT20FYA7R')
                    }
                    environment {
                        ANDROID_HOME = "/Users/couchbase/Library/Android/sdk"
                        JAVA_HOME = "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
                        PATH = "\$JAVA_HOME/bin:\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/tools:\$ANDROID_HOME/tools/bin:/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        TS_ARTIFACTS_DIR = 'android'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        // Unlock keychain:
                        withCredentials([string(credentialsId: 'mobile-qe', variable: 'KEYCHAIN_PASSWORD')]) {
                            sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        }
                        echo "=== Run C Android Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/c/run_test.sh ${params.CBL_VERSION} android ${params.SGW_VERSION}"
                        }
                        echo "=== C Android Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown C Android Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/c/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/c_android/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== C Android Test Teardown Complete"
                        }
                    }
                }
                stage('Linux') {
                    agent { label 'linux-c' }
                    options {
                        lock('linux-c')
                    }
                    environment {
                        TS_ARTIFACTS_DIR = 'c'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        echo "=== Run C Linux Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/c/run_test.sh ${params.CBL_VERSION} linux_x86_64 ${params.SGW_VERSION}"
                        }
                        echo "=== C Linux Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown C Linux Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/c/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/c_linux/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== C Linux Test Teardown Complete"
                        }
                    }
                }
                stage('Windows') {
                    agent { label 'net-windows' }
                    options {
                        lock('net-windows')
                    }
                    environment {
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        echo "=== Run C Windows Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            powershell "jenkins\\pipelines\\QE\\c\\run_test.ps1 -Version ${params.CBL_VERSION} -SgwVersion ${params.SGW_VERSION}"
                        }
                        echo "=== C Windows Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown C Windows Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                powershell 'jenkins\\pipelines\\QE\\c\\teardown.ps1'
                            }
                            archiveArtifacts artifacts: 'tests\\QE\\c_windows\\**\\*', fingerprint: true, allowEmptyArchive: true
                            echo "=== C Windows Test Teardown Complete"
                        }
                    }
                }
            }
        }
    }
}
