
pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '3.2.3', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.2.3', description: "The version of Sync Gateway to download")
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "java ${params.CBL_VERSION} (#${currentBuild.number})"
                }
            }
        }

        stage('Prebuild Servers') {
            steps {
                script {
                    def platforms = [
                        'jak_desktop', 'jak_webservice'
                    ]
                    def parallelBuilds = [:]
                    for(p in platforms) {
                        def platform = p
                        parallelBuilds[platform] = {
                            build job: 'prebuild-test-server',
                            parameters: [
                                string(name: 'TS_PLATFORM', value: platform),
                                string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                            ],
                            wait: true,
                            propagate: true
                        }
                    }
                    parallel parallelBuilds
                }
            }
        }

        stage('Tests') {
            parallel {
                stage('Linux Desktop Test') {
                    agent { label 'cbl-java-desktop-centos-7' }
                    environment {
                        KEYCHAIN_PASSWORD = credentials('mobile-qe-keychain')
                        PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        AWS_PROFILE = "mobile-for-now"
                        TS_ARTIFACTS_DIR = 'java_desktop'
                    }
                    steps {
                        echo "=== Run Linux Desktop Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/java/desktop/run_test.sh ${params.CBL_VERSION} ${params.SGW_VERSION} ~/.ssh/jborden.pem"
                        }
                        echo "=== Linux Desktop Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown Linux Desktop Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/java/desktop/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/java_desktop/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== Linux Desktop Test Teardown Complete"
                        }
                    }
                }
                stage('Linux Web Service Test') {
                    agent { label 'cbl-java-webservice-centos-7' }
                    environment {
                        KEYCHAIN_PASSWORD = credentials('mobile-qe-keychain')
                        PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        AWS_PROFILE = "mobile-for-now"
                        TS_ARTIFACTS_DIR = 'java_webservice'
                    }
                    steps {
                        echo "=== Run Linux Web Service Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/java/webservice/run_test.sh ${params.CBL_VERSION} ${params.SGW_VERSION} ~/.ssh/jborden.pem"
                        }
                        echo "=== Linux Web Service Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown Linux Web Service Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/java/webservice/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/java_webservice/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== Linux Web Service Test Teardown Complete"
                        }
                    }
                }
            }
        }
    }
}
