pipeline {
    agent none
    parameters {
        string(name: 'CBL_VERSION', defaultValue: '3.3.0', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.3.0', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
    }
    options {
        timeout(time: 150, unit: 'MINUTES')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    
                    currentBuild.displayName = "Java Desktop CBL:${params.CBL_VERSION} (#${currentBuild.number})"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
//         stage('Prebuild Servers') {
//             steps {
//                 build job: 'prebuild-test-server',
//                 parameters: [
//                     string(name: 'TS_PLATFORM', value: 'jak_desktop'),
//                     string(name: 'CBL_VERSION', value: params.CBL_VERSION),
//                 ],
//                 wait: true,
//                 propagate: true
//             }
//         }
        stage('Run Tests') {
            parallel {
                stage('macOS Desktop') {
                    agent { label 'mac-mini-new' }
                    options {
                        lock('mac-mini-new')
                    }
                    environment {
                        KEYCHAIN_PASSWORD = credentials('mobile-qe')
                        PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                        TS_ARTIFACTS_DIR = 'java_macos_desktop'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        echo "=== Run macOS Desktop Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/java/desktop/run_test.sh ${params.CBL_VERSION} ${params.SGW_VERSION}"
                        }
                        echo "=== macOS Desktop Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown macOS Desktop Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/java/desktop/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/java_macos_desktop/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== macOS Desktop Test Teardown Complete"
                        }
                    }
                }
                stage('Windows Desktop') {
                    agent { label 'net-windows' }
                    options {
                        lock('net-windows')
                    }
                    environment {
                        TS_ARTIFACTS_DIR = 'java_windows_desktop'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        echo "=== Run Windows Desktop Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            bat '''
                            "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" ^
                            -NoProfile ^
                            -ExecutionPolicy Bypass ^
                            -File jenkins\\pipelines\\QE\\java\\desktop\\run_test.ps1 ^
                            -Version %CBL_VERSION% ^
                            -SgwVersion %SGW_VERSION%
                            '''                        }
                        echo "=== Windows Desktop Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown Windows Desktop Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                bat '''
                                "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" ^
                                -NoProfile ^
                                -ExecutionPolicy Bypass ^
                                -File jenkins\\pipelines\\QE\\java\\desktop\\teardown.ps1
                                '''
                            }
                            archiveArtifacts artifacts: 'tests\\QE\\java_windows_desktop\\**\\*', fingerprint: true, allowEmptyArchive: true
                            echo "=== Windows Desktop Test Teardown Complete"
                        }
                    }
                }
                stage('Linux Desktop') {
                    agent { label 'linux-java' }
                    options {
                        lock('linux-java')
                    }
                    environment {
                        TS_ARTIFACTS_DIR = 'java_desktop'
                        TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
                    }
                    steps {
                        echo "=== Run Linux Desktop Tests"
                        timeout(time: 120, unit: 'MINUTES') {
                            sh "jenkins/pipelines/QE/java/desktop/run_test.sh ${params.CBL_VERSION} ${params.SGW_VERSION}"
                        }
                        echo "=== Linux Desktop Tests Complete"
                    }
                    post {
                        always {
                            echo "=== Teardown Linux Desktop Tests"
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/QE/java/desktop/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/QE/java_desktop/**/*', fingerprint: true, allowEmptyArchive: true
                            echo "=== Linux Desktop Test Teardown Complete"
                        }
                    }
                }
            }
        }
    }
}
