version: "3.9"
services:
  agent:
    image: jenkins/ssh-agent
    container_name: agent
    restart: unless-stopped
    ports:
      - "2200:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}