pipeline {
    agent none
    parameters {
        string(name: 'CBL_VERSION', defaultValue: '3.3.0', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.2.4', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "iOS CBL:${params.CBL_VERSION} (#${currentBuild.number})"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
        stage('Prebuild Servers') {
            steps {
                build job: 'prebuild-test-server',
                parameters: [
                    string(name: 'TS_PLATFORM', value: 'swift_ios'),
                    string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                ],
                wait: true,
                propagate: true
            }
        }
        stage('Run Test') {
            agent { label 'qe-mac-india' }
            environment {
                KEYCHAIN_PASSWORD = credentials('mobile-qe')
                PATH = "/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                AWS_PROFILE = "mobile-qe"
                TS_ARTIFACTS_DIR = 'ios'
                TS_DATASET_VERSION = "${params.TS_DATASET_VERSION}"
            }
            steps {
                // Unlock keychain:
                sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                echo "Run iOS Test"
                timeout(time: 60, unit: 'MINUTES') {
                    sh "jenkins/pipelines/QE/ios/test.sh ${params.CBL_VERSION} ${params.SGW_VERSION}"
                }
            }
            post {
                always {
                    echo "Teardown iOS Test"
                    timeout(time: 5, unit: 'MINUTES') {
                        sh "jenkins/pipelines/QE/ios/teardown.sh"
                    }
                    archiveArtifacts artifacts: 'tests/QE/ios/**/*', fingerprint: true, allowEmptyArchive: true
                }
            }
        }
    }
}