import ssl
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from aiohttp import ClientSession, TCPConnector, web
from cbltest.api.syncgateway import _SGW_CA_CERT, SyncGateway
from cbltest.api.x509_certificate import (
    CertKeyPair,
    create_ca_certificate,
    create_leaf_certificate,
)
from conftest import patch_bootstrap
from cryptography import x509
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
)

_CERT_DIR = Path(__file__).parents[2] / "environment" / "aws" / "sgw_setup" / "cert"
_CA_CERT_FILE = _CERT_DIR / "ca_cert.pem"
_SG_CERT_FILE = _CERT_DIR / "sg_cert.pem"
_SG_KEY_FILE = _CERT_DIR / "sg_key.pem"

# Certificates are regenerated by hand, so fail a year ahead of expiry to leave time to act.
_MINIMUM_REMAINING = timedelta(days=365)

_SKIP_REASON = f"{_CERT_DIR} not available (cbltest installed outside the repo)"


@asynccontextmanager
async def _tls_server(cert_file: Path, key_file: Path) -> AsyncIterator[int]:
    """Serve HTTPS on an ephemeral loopback port using the given identity, yielding the port."""
    server_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    server_context.load_cert_chain(certfile=cert_file, keyfile=key_file)

    async def handler(request: web.Request) -> web.Response:
        return web.Response(text="ok")

    app = web.Application()
    app.router.add_get("/", handler)
    runner = web.AppRunner(app)
    await runner.setup()
    try:
        await web.TCPSite(runner, "127.0.0.1", 0, ssl_context=server_context).start()
        yield next(iter(runner.addresses))[1]
    finally:
        await runner.cleanup()


def _write_pem(pair: CertKeyPair, directory: Path) -> tuple[Path, Path]:
    """Write a certificate and its private key to PEM files, returning both paths."""
    cert_file = directory / "cert.pem"
    key_file = directory / "key.pem"
    cert_file.write_bytes(pair.pem_bytes())
    key_file.write_bytes(
        pair.private_key.private_bytes(
            encoding=Encoding.PEM,
            format=PrivateFormat.PKCS8,
            encryption_algorithm=NoEncryption(),
        )
    )
    return cert_file, key_file


def _assert_signs_certificates(certificate: x509.Certificate) -> None:
    """Assert a CA carries the extensions strict verification demands of a signer."""
    basic_constraints = certificate.extensions.get_extension_for_class(x509.BasicConstraints)
    assert basic_constraints.critical
    assert basic_constraints.value.ca

    key_usage = certificate.extensions.get_extension_for_class(x509.KeyUsage)
    assert key_usage.critical
    assert key_usage.value.key_cert_sign
    assert key_usage.value.crl_sign


class TestSyncGatewayCaCertificate:
    """The CA backing every TLS connection to a deployed Sync Gateway.  Python 3.13 enables
    ssl.VERIFY_X509_STRICT by default, which rejects a CA carrying no keyUsage with
    "CA cert does not include key usage extension" partway through the handshake."""

    def test_inlined_copy_matches_the_source_file(self) -> None:
        if not _CA_CERT_FILE.is_file():
            pytest.skip(_SKIP_REASON)

        # environment/ is not shipped with the cbltest package, so the CA is inlined by hand.
        assert _SGW_CA_CERT.strip() == _CA_CERT_FILE.read_text().strip(), (
            f"_SGW_CA_CERT in cbltest/api/syncgateway.py has drifted from {_CA_CERT_FILE}. "
            "Re-copy the file contents into the constant."
        )

    def test_carries_the_extensions_strict_verification_requires(self) -> None:
        _assert_signs_certificates(x509.load_pem_x509_certificate(_SGW_CA_CERT.encode()))

    @pytest.mark.asyncio
    async def test_client_trusts_the_leaf_sync_gateway_serves(self) -> None:
        # Reproduces a real run's handshake, deployment and all, without AWS.
        if not _SG_CERT_FILE.is_file() or not _SG_KEY_FILE.is_file():
            pytest.skip(_SKIP_REASON)

        async with _tls_server(_SG_CERT_FILE, _SG_KEY_FILE) as port:
            # SyncGateway's constructor pings the host over plain HTTP; not what this tests.
            with patch_bootstrap():
                sync_gateway = SyncGateway(url="127.0.0.1", username="user", password="pass", port=port, secure=True)

            session = sync_gateway._create_session(True, "https://", "127.0.0.1", port, None)
            async with session, session.get("/") as response:
                assert response.status == 200


class TestGeneratedCertificates:
    """Certificates minted at runtime by x509_certificate.py for listeners and multipeer."""

    def test_ca_carries_the_extensions_strict_verification_requires(self) -> None:
        _assert_signs_certificates(create_ca_certificate("Test CA").certificate)

    def test_self_signed_leaf_stays_usable_as_its_own_trust_anchor(self) -> None:
        # Peers are handed this certificate as their trust anchor, so it deliberately carries
        # neither basicConstraints nor keyUsage; CA:FALSE would make them reject it.
        leaf = create_leaf_certificate("Test Server 0")

        with pytest.raises(x509.ExtensionNotFound):
            leaf.certificate.extensions.get_extension_for_class(x509.BasicConstraints)
        with pytest.raises(x509.ExtensionNotFound):
            leaf.certificate.extensions.get_extension_for_class(x509.KeyUsage)

    @pytest.mark.asyncio
    async def test_ca_issued_leaf_verifies_strictly_over_tls(self, tmp_path: Path) -> None:
        ca = create_ca_certificate("Test CA")
        leaf = create_leaf_certificate("Test Server 0", issuer_data=ca)
        cert_file, key_file = _write_pem(leaf, tmp_path)

        async with _tls_server(cert_file, key_file) as port:
            client_context = ssl.create_default_context(cadata=ca.pem_bytes().decode())
            assert client_context.verify_flags & ssl.VERIFY_X509_STRICT
            # These identities are matched by certificate rather than by name, and carry no
            # subjectAltName, so hostname checking is not part of this test.
            client_context.check_hostname = False

            async with (
                ClientSession(connector=TCPConnector(ssl=client_context)) as session,
                session.get(f"https://127.0.0.1:{port}/") as response,
            ):
                assert response.status == 200


def _collect_certificates() -> list[tuple[str, x509.Certificate]]:
    """
    Return every certificate the harness ships, as (label, certificate) pairs.

    Covers each PEM in the Sync Gateway cert directory, one entry per certificate so that a
    bundle such as sg_fullchain.pem contributes all of its own, plus the copy inlined in
    syncgateway.py.  Private key PEMs hold no certificate and are skipped.
    """
    collected: list[tuple[str, x509.Certificate]] = []

    if _CERT_DIR.is_dir():
        for pem_file in sorted(_CERT_DIR.glob("*.pem")):
            contents = pem_file.read_bytes()
            if b"BEGIN CERTIFICATE" not in contents:
                continue

            certificates = x509.load_pem_x509_certificates(contents)
            for index, certificate in enumerate(certificates):
                suffix = f"[{index}]" if len(certificates) > 1 else ""
                collected.append((f"{pem_file.name}{suffix}", certificate))

    collected.append(("syncgateway.py::_SGW_CA_CERT", x509.load_pem_x509_certificate(_SGW_CA_CERT.encode())))
    return collected


_CERTIFICATES = _collect_certificates()


class TestCertificateExpiry:
    """Nothing renews these certificates, so expiry has to surface as a test failure."""

    def test_every_shipped_certificate_was_discovered(self) -> None:
        if not _CERT_DIR.is_dir():
            pytest.skip(_SKIP_REASON)

        # Without this, restructuring the cert directory would silently empty the sweep below.
        discovered = {name for name, _ in _CERTIFICATES}
        assert {"ca_cert.pem", "sg_cert.pem", "syncgateway.py::_SGW_CA_CERT"} <= discovered

    @pytest.mark.parametrize(("name", "certificate"), _CERTIFICATES, ids=[name for name, _ in _CERTIFICATES])
    def test_certificate_is_valid_for_at_least_another_year(self, name: str, certificate: x509.Certificate) -> None:
        remaining = certificate.not_valid_after_utc - datetime.now(UTC)
        assert remaining >= _MINIMUM_REMAINING, (
            f"{name} (subject {certificate.subject.rfc4514_string()}) expires "
            f"{certificate.not_valid_after_utc:%Y-%m-%d}, in {remaining.days} days. "
            "Regenerate it with environment/aws/sgw_setup/cert/gen_cert.sh."
        )
