networks:
  dinonet:
    external: true

services:
  cbl-test-cbs1:
    build:
      context: ./cbs
      args:
        - COUCHBASE_VERSION=${COUCHBASE_VERSION:-7.6.4-5147}
        - COUCHBASE_CONTAINER_PATH=${COUCHBASE_CONTAINER_PATH:-ghcr.io/cb-vanilla/server:}
    networks:
      - dinonet
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"
      - "18091:18091"
      - "18092:18092"
      - "18093:18093"
      - "18094:18094"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/admin/ping"]
      interval: 1s
      timeout: 10s
      retries: 120
  cbl-test-sg1:
    build:
      context: ./sg
      args:
        - SG_DEB=${SG_DEB:-https://latestbuilds.service.couchbase.com/builds/latestbuilds/sync_gateway/4.0.0/87/couchbase-sync-gateway-enterprise_4.0.0-87_<ARCH>.deb}
    environment:
      SSL: false
      CBS_HOSTNAME: cbl-test-cbs1
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:4984/_ping"]
      interval: 1s
      timeout: 10s
      retries: 120
    depends_on:
      cbl-test-cbs1:
        condition: service_healthy
    networks:
      - dinonet
    ports:
      - "4984:4984"
      - "4985:4985"
  cbl-test-cbs2:
    build:
      context: ./cbs
      args:
        - COUCHBASE_VERSION=${COUCHBASE_VERSION:-7.6.4-5147}
        - COUCHBASE_CONTAINER_PATH=${COUCHBASE_CONTAINER_PATH:-ghcr.io/cb-vanilla/server:}
    networks:
      - dinonet
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"
      - "18091:18091"
      - "18092:18092"
      - "18093:18093"
      - "18094:18094"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/admin/ping"]
      interval: 1s
      timeout: 10s
      retries: 120
  cbl-test-sg2:
    build:
      context: ./sg
      args:
        - SG_DEB=${SG_DEB:-https://latestbuilds.service.couchbase.com/builds/latestbuilds/sync_gateway/4.0.0/87/couchbase-sync-gateway-enterprise_4.0.0-87_<ARCH>.deb}
    environment:
      SSL: false
      CBS_HOSTNAME: cbl-test-cbs2
    networks:
      - dinonet
    ports:
      - "4984:4984"
      - "4985:4985"
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:4984/_ping"]
      interval: 1s
      timeout: 10s
      retries: 120
    depends_on:
      cbl-test-cbs2:
        condition: service_healthy
  cbl-test-nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx/nginx-2node.conf:/etc/nginx/nginx.conf
    networks:
      - dinonet
    ports:
      - "4984:4984"
      - "4985:4985"
    depends_on:
      cbl-test-cbs1:
        condition: service_healthy
      cbl-test-cbs2:
        condition: service_healthy
      cbl-test-sg1:
        condition: service_healthy
      cbl-test-sg2:
        condition: service_healthy
