services:
  cbl-test-cbs:
    build:
      context: ./cbs
      args:
        - COUCHBASE_VERSION=${COUCHBASE_VERSION:-7.6.3}
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11207:11207"
      - "11210:11210"
      - "11211:11211"
      - "18091:18091"
      - "18092:18092"
      - "18093:18093"
      - "18094:18094"

  cbl-test-sg:
    build:
      context: ./sg
      args:
        - SG_DEB=${SG_DEB:-https://packages.couchbase.com/releases/couchbase-sync-gateway/3.2.0/couchbase-sync-gateway-enterprise_3.2.0_<ARCH>.deb}
    environment:
      SSL: true
    ports:
      - "4984:4984"
      - "4985:4985"
    depends_on: 
      - "cbl-test-cbs"

  cbl-test-logslurp:
    build:
      context: ./LogSlurp
      dockerfile: LogSlurp/Dockerfile
    ports:
      - "8180:8180"
