pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '1.0.1', description: 'cbl-reactnative Version')
        string(name: 'CBL_BUILD', defaultValue: '', description: 'cbl-reactnative Build Number')
        string(name: 'SGW_VERSION', defaultValue: '', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
        booleanParam(name: 'SKIP_PREBUILD', defaultValue: false, description: 'Skips prebuild job')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.CBL_BUILD == '') { error "CBL_BUILD is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "rn-android-${CBL_EDITION} ${params.CBL_VERSION}-${params.CBL_BUILD} (#${currentBuild.number})"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
        stage('Prebuild Server') {
            steps {
                script {
                    if (!params.SKIP_PREBUILD)
                    {
                        build job: 'prebuild-test-server',
                        parameters: [
                            string(name: 'TS_PLATFORM', value: 'reactnative_android'),
                            string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                            string(name: 'CBL_BUILD', value: params.CBL_BUILD),
                            string(name: 'BRANCH', value: "tdk_reactnative"),
                        ],
                        wait: true,
                        propagate: true
                    }
                }
            }
        }
        stage('Run Test') {
            agent { label 'mob-e2e-mac-01' }
            options {
                lock("mob-e2e-android-01")
            }
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "*/tdk_reactnative"]],
                    userRemoteConfigs: [[url: 'https://github.com/couchbaselabs/couchbase-lite-tests']]
                ])
                echo "Run React Native Android Tests"
                timeout(time: 60, unit: 'MINUTES') {
                    sh """
                        jenkins/pipelines/dev_e2e/reactnative_android/test.sh "${params.CBL_VERSION}-${params.CBL_BUILD}" "${params.SGW_VERSION}" ${params.TS_DATASET_VERSION}
                    """
                }
            }
            post {
                always {
                    echo "Teardown React Native Android Tests"
                    timeout(time: 5, unit: 'MINUTES') {
                        sh 'jenkins/pipelines/dev_e2e/reactnative_android/teardown.sh'
                    }
                    archiveArtifacts artifacts: 'tests/dev_e2e/session.log', fingerprint: true, allowEmptyArchive: true
                    archiveArtifacts artifacts: 'tests/dev_e2e/http_log/*', fingerprint: true, allowEmptyArchive: true
                }
            }
        }
    }
}
