pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '3.2.0', description: 'Couchbase Lite Version')
        string(name: 'CBL_BUILD', defaultValue: '', description: 'Couchbase Lite Build Number')
        string(name: 'SGW_VERSION', defaultValue: '', description: "The version of Sync Gateway to download")
        string(name: 'TS_DATASET_VERSION', defaultValue: '4.0', description: 'The version of the dataset to use on the test servers')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.CBL_BUILD == '') { error "CBL_BUILD is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "${params.CBL_VERSION}-${params.CBL_BUILD}"
                    currentBuild.description = "SGW: ${params.SGW_VERSION}"
                }
            }
        }
        stage('Prebuild Servers') {
            steps {
                script {
                    def platforms = [
                        'dotnet_windows', 'dotnet_ios', 'dotnet_android', 'dotnet_macos'
                    ]
                    def parallelBuilds = [:]
                    for(p in platforms) {
                        // Groovy stupidness.  Need to set a local variable here
                        // to avoid late binding (all jobs use dotnet_macos).
                        def platform = p
                        parallelBuilds[platform] = {
                            build job: 'prebuild-test-server',
                            parameters: [
                                string(name: 'TS_PLATFORM', value: platform),
                                string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                                string(name: 'CBL_BUILD', value: params.CBL_BUILD)
                            ],
                            wait: true,
                            propagate: true
                        }
                    }
                    parallel parallelBuilds
                }
            }
        }
        stage('Run Tests') {
            parallel {
                stage("Windows") {
                    agent { label 'mob-e2e-win-01' }
                    options {
                        lock("mob-e2e-win-01")
                    }
                    environment {
                        TS_ARTIFACTS_DIR = 'windows'
                    }
                    steps {
                        timeout(time: 60, unit: 'MINUTES') {
                            pwsh "jenkins\\pipelines\\dev_e2e\\dotnet\\run_test.ps1 -Version ${params.CBL_VERSION}-${params.CBL_BUILD} -SgwVersion ${params.SGW_VERSION} -DatasetVersion ${params.TS_DATASET_VERSION}"
                        }
                    }
                    post { 
                        always { 
                            timeout(time: 5, unit: 'MINUTES') {
                                pwsh 'jenkins\\pipelines\\dev_e2e\\dotnet\\teardown.ps1'
                            }
                            archiveArtifacts artifacts: 'tests\\dev_e2e\\windows\\**', fingerprint: true, allowEmptyArchive: true
                        }
                    }
                }
                stage("Mac Catalyst") {
                    agent { label 'mob-e2e-mac-01' }
                    options {
                        lock("mob-e2e-mac-01")
                    }
                    environment {
                        KEYCHAIN_PASSWORD = credentials('mob-e2e-mac-01-keychain-password') 
                        DEVELOPER_DIR="/Applications/Xcode.app"
                        MD_APPLE_SDK_ROOT="/Applications/Xcode.app"
                        TS_ARTIFACTS_DIR = 'macos'
                    }
                    steps {
                        sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        timeout(time: 60, unit: 'MINUTES') {
                            sh "jenkins/pipelines/dev_e2e/dotnet/run_test.sh ${params.CBL_VERSION}-${params.CBL_BUILD} macos '${params.SGW_VERSION}' ${params.TS_DATASET_VERSION} ~/.ssh/jborden.pem"
                        }
                    }
                    post { 
                        always { 
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/dev_e2e/dotnet/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/dev_e2e/macos/**', fingerprint: true, allowEmptyArchive: true
                        }
                    }
                }
                stage('iOS') {
                    options {
                        lock("mob-e2e-iphone-01")
                    }
                    environment { 
                        KEYCHAIN_PASSWORD = credentials('mob-e2e-mac-01-keychain-password') 
                        DEVELOPER_DIR="/Applications/Xcode.app"
                        MD_APPLE_SDK_ROOT="/Applications/Xcode.app"
                        TS_ARTIFACTS_DIR = 'ios'
                    }
                    agent { label 'mob-e2e-mac-01' }
                    steps {
                        sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        timeout(time: 60, unit: 'MINUTES') {
                            sh "jenkins/pipelines/dev_e2e/dotnet/run_test.sh ${params.CBL_VERSION}-${params.CBL_BUILD} ios '${params.SGW_VERSION}' ${params.TS_DATASET_VERSION}"
                        }
                    }
                    post {
                        always {
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/dev_e2e/dotnet/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/dev_e2e/ios/**', fingerprint: true, allowEmptyArchive: true
                        }
                    }
                }
                stage('Android') {
                    options {
                        lock("mob-e2e-android-01") 
                    }
                    agent { label 'mob-e2e-mac-01' }
                    environment {
                        TS_ARTIFACTS_DIR = 'android'
                    }
                    steps {
                        timeout(time: 60, unit: 'MINUTES') {
                            sh "jenkins/pipelines/dev_e2e/dotnet/run_test.sh ${params.CBL_VERSION}-${params.CBL_BUILD} android '${params.SGW_VERSION}' ~/.ssh/jborden.pem"
                        }
                    }
                    post {
                        always {
                            timeout(time: 5, unit: 'MINUTES') {
                                sh 'jenkins/pipelines/dev_e2e/dotnet/teardown.sh'
                            }
                            archiveArtifacts artifacts: 'tests/dev_e2e/android/**', fingerprint: true, allowEmptyArchive: true
                        }
                    }
                }
            }
        }
    }
    post {
        failure {
            mail bcc: '', body: "Project: <a href='${env.BUILD_URL}'>${env.JOB_NAME}</a> has failed!", cc: '', charset: 'UTF-8', from: 'jenkins@couchbase.com', mimeType: 'text/html', replyTo: 'no-reply@couchbase.com', subject: "${env.JOB_NAME} failed", to: "jim.borden@couchbase.com";
        }
    }
}
