<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AssemblyVersion>2.0.3</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Couchbase.Lite.Enterprise" Version="4.1.2-b0002" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
        <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
        <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="sly" Version="3.8.1" />
    </ItemGroup>

</Project>
