@startuml "Architecture"

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v19.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Containers/ElasticContainerServiceContainer3.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!include AWSPuml/Groups/VPC.puml

VPCInternetGateway(igw, "Internet Gateway", "")
VPCGroup(vpc, "Internal Network") {
    ElasticContainerServiceContainer3(cbs, "Couchbase Server", "")
    ElasticContainerServiceContainer3(sgw, "Sync Gateway", "")
}

sgw <--> cbs : " Public and Private\nPort Access"
vpc <--> igw : " Public Port Access (4984, 4985, 8091, etc)"

@enduml