@startuml architecture-4

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v19.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Containers/ElasticContainerServiceContainer3.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!include AWSPuml/Groups/VPC.puml

skinparam componentStyle uml2
skinparam linetype ortho
skinparam node {
    BackgroundColor #E0E0E0
    BorderColor Black
    FontName "Courier New"
}
skinparam component {
    BackgroundColor #FFFFFF
    BorderColor Black
    FontName "Courier New"
}
skinparam defaultTextAlignment center

node "Control Machine" as Control {
    component "Orchestrator"
    component "TDK"
}

' Bottom layer: Mobile Device
node "Mobile Device\n(USB-connected)" as Mobile {
    component "Test Server"
}

    VPCInternetGateway(igw, "IGW\nInternet\nGateway", "")
VPCGroup(vpc, "Subnet\n10.0.1.0/24") {
    ElasticContainerServiceContainer3(cbs, "Couchbase Server", "")
    ElasticContainerServiceContainer3(sgw, "Sync Gateway", "")
    ElasticContainerServiceContainer3(ls, "Log Slurp", "")
}

Control -down-> Mobile
sgw <--> cbs : "Private and \n Public Port Access  "
igw <--> vpc
TDK <--> igw
TDK <-left-> Mobile

@enduml