pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '3.2.0', description: 'Couchbase Lite Version')
        string(name: 'CBL_BUILD', defaultValue: '', description: 'Couchbase Lite Build Number')
    }
    options { timeout(time: 30, unit: 'MINUTES') }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.CBL_BUILD == '') { error "CBL_BUILD is required" }
                    currentBuild.displayName = "android-${CBL_EDITION}-${params.CBL_VERSION}-${params.CBL_BUILD} (#${currentBuild.number})"
                }
            }
        }
        stage('Android') {
            agent { label 'mob-e2e-mac-01' }
            steps {
                // Run tests:
                echo "Run Android Tests"
                sh """
                    #export ANDROID_SERIAL=14151JEC204776
                    jenkins/pipelines/android/android_tests.sh ${params.CBL_EDITION} ${params.CBL_VERSION} ${params.CBL_BUILD}
                """
            }
            post {
                always {
                    echo "Teardown Android Tests"
                    sh '''
                        #export ANDROID_SERIAL=14151JEC204776
                        jenkins/pipelines/android/android_teardown.sh
                    '''
                }
            }
        }
    }
}
