pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '3.3.0', description: 'Couchbase Lite Version (build number will be fetched if not provided)')
        string(name: 'SGW_VERSION', defaultValue: '3.2.3', description: "The version of Sync Gateway to download")
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.SGW_VERSION == '') { error "SGW_VERSION is required" }
                    currentBuild.displayName = "android ${params.CBL_VERSION} (#${currentBuild.number})"
                }
            }
        }
        stage('Prebuild Servers') {
            steps {
                build job: 'prebuild-test-server',
                parameters: [
                    string(name: 'TS_PLATFORM', value: 'jak_android'),
                    string(name: 'CBL_VERSION', value: params.CBL_VERSION),
                ],
                wait: true,
                propagate: true
            }
        }
        stage('Android') {
            agent { label 'mac-laptop1-new' }
            environment {
                KEYCHAIN_PASSWORD = credentials('mobile-qe-keychain')
                ANDROID_HOME = "/Users/couchbase/Library/Android/sdk"
                PATH = "\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/tools:\$ANDROID_HOME/tools/bin:/opt/homebrew/opt/python@3.10/bin:/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
                AWS_PROFILE = "mobile-for-now"
                TS_ARTIFACTS_DIR = 'android'
            }
            steps {
                // Unlock keychain:
                sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                echo "Run Android Tests"
                timeout(time: 120, unit: 'MINUTES') {
                    sh """
                        jenkins/pipelines/QE/android/android_tests.sh "${params.CBL_VERSION}" "${params.SGW_VERSION}" ~/.ssh/jborden.pem
                    """
                }
            }
            post {
                always {
                    echo "Teardown Android Tests"
                    timeout(time: 5, unit: 'MINUTES') {
                        sh "jenkins/pipelines/QE/android/android_teardown.sh"
                    }
                    archiveArtifacts artifacts: 'tests/QE/android/**/*', fingerprint: true, allowEmptyArchive: true
                }
            }
        }
    }
}
