pipeline {
    agent none
    parameters {
        choice(name: 'CBL_EDITION', choices: ['enterprise', 'community'], description: 'Couchbase Lite Edition')
        string(name: 'CBL_VERSION', defaultValue: '3.2.0', description: 'Couchbase Lite Version')
        string(name: 'CBL_BUILD', defaultValue: '', description: 'Couchbase Lite Build Number')
        string(name: 'SGW_URL', defaultValue: '', description: "The url of Sync Gateway to download")
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    if (params.CBL_VERSION == '') { error "CBL_VERSION is required" }
                    if (params.CBL_BUILD == '') { error "CBL_BUILD is required" }
                    currentBuild.displayName = "${params.CBL_VERSION}-${params.CBL_BUILD}-${CBL_EDITION} (#${currentBuild.number})"
                }
            }
        }
        stage('Run Tests') {
            parallel {
                stage('macOS') {
                    agent { label 'mob-e2e-mac-01' }
                    steps {
                        echo "Run macOS Test"
                        sh "jenkins/pipelines/c/macos_test.sh ${params.CBL_EDITION} ${params.CBL_VERSION} ${params.CBL_BUILD}"
                    }
                    post { 
                        always { 
                            echo "Teardown macOS Test"
                            sh 'jenkins/pipelines/c/macos_teardown.sh'
                        }
                    }
                }
                stage('iOS') {
                    agent { label 'mob-e2e-mac-01' }
                    environment { 
                        KEYCHAIN_PASSWORD = credentials('mob-e2e-mac-01-keychain-password') 
                    }
                    steps {
                        // Unlock keychain:
                        sh 'security unlock-keychain -p ${KEYCHAIN_PASSWORD} ~/Library/Keychains/login.keychain-db'
                        echo "Run iOS Test"
                        sh "jenkins/pipelines/c/ios_test.sh ${params.CBL_EDITION} ${params.CBL_VERSION} ${params.CBL_BUILD}"
                    }
                    post { 
                        always { 
                            echo "Teardown iOS Test"
                            sh 'jenkins/pipelines/c/ios_teardown.sh'
                        }
                    }
                }
                stage('linux') {
                    agent { label 'mob-e2e-deb-02' }
                    steps {
                        echo "Run linux Test"
                        sh "jenkins/pipelines/c/linux_test.sh ${params.CBL_EDITION} ${params.CBL_VERSION} ${params.CBL_BUILD}"
                    }
                    post { 
                        always { 
                            echo "Teardown linux Test"
                            sh 'jenkins/pipelines/c/linux_teardown.sh'
                        }
                    }
                }
            }
        }
    }
    post {
        failure {
            mail bcc: '', body: "Project: <a href='${env.BUILD_URL}'>${env.JOB_NAME}</a> has failed!", cc: '', charset: 'UTF-8', from: 'jenkins@couchbase.com', mimeType: 'text/html', replyTo: 'no-reply@couchbase.com', subject: "${env.JOB_NAME} failed", to: "pasin@couchbase.com";
        }
    }
}