name: C TestServer Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CBL_EDITION: enterprise
  CBL_VERSION: 3.1.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # - name: Build macOS
    #   if: runner.os == 'macOS'
    #   working-directory: ${{github.workspace}}/servers/c
    #   shell: bash
    #   run: ./scripts/build_macOS.sh ${{env.CBL_EDITION}} ${{env.CBL_VERSION}}

    # - name: Build iOS
    #   if: runner.os == 'macOS'
    #   working-directory: ${{github.workspace}}/servers/c
    #   shell: bash
    #   run: ./scripts/build_ios.sh simulator ${{env.CBL_EDITION}} ${{env.CBL_VERSION}}

    - name: Build Linux
      if: runner.os == 'Linux'
      working-directory: ${{github.workspace}}/servers/c
      shell: bash
      run: ./scripts/build_linux.sh ${{env.CBL_EDITION}} ${{env.CBL_VERSION}}

    - name: Build Windows
      if: runner.os == 'Windows'
      working-directory: ${{github.workspace}}/servers/c
      shell: pwsh
      run: ./scripts/build_wins.ps1 ${{env.CBL_EDITION}} ${{env.CBL_VERSION}}